config/routes.rb
Rails.application.routes.draw do

  resources :nisetts,only:[:index,:new,:create,:edit,:update,:destroy]do 
    collection do
      post :confirm
    end
  end
  resources :messages,only:[:new,:create] do
    collection do
      post :confirm
    end
  end
  
  root'top#index'
  

end

app/models/message.rb
class Message < ActiveRecord::Base
    validates:content,presence:true
end

app/models/nisett.rb
class Nisett < ActiveRecord::Base
    
    validates:content,presence:true,length:{maximum: 140}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    if params[:back]
      @message = Message.new(messagess_params)
    else
      @message = Message.new
    end
  end
  def create
    @message = Message.new(messages_params)
    if @message.save
      redirect_to root_path,notice:"メッセージを送信しました！"
    else
      render'new'
    end
  end
  def confirm
    @message = Message.new(messages_params)
    render:new if @message.invalid?
  end
  
  private
    def messages_params
      params.require(:message).permit(:name,:email,:content)
    end
end

app/controllers/nisetts_controller.rb
class NisettsController < ApplicationController
  before_action :set_nisett,only:[:edit,:update,:destroy]
  
  def index
    @nisetts = Nisett.all
  end
  
  def new
    if params[:back]
    @nisett = Nisett.new(nisetts_params)
    else
    @nisett = Nisett.new
    end
  end
  
  def create
    @nisett = Nisett.new(nisetts_params)
    if @nisett.save
      redirect_to nisetts_path,notice:"投稿しました！"
    else
      render'new'
    end
  end
  
  def edit
  end
  
  def update
    if @nisett.update(nisetts_params)
    redirect_to nisetts_path,notice:"編集しました！"
    else
      render'edit'
    end
  end
  
  def destroy
    @nisett.destroy
    redirect_to nisetts_path,notice:"削除しました！"
  end
  
  def confirm
    @nisett = Nisett.new(nisetts_params)
    render :new if @nisett.invalid?
  end
  
  private
  def nisetts_params
    params.require(:nisett).permit(:content)
  end
  def set_nisett
    @nisett = Nisett.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/nisetts_helper.rb
module NisettsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_nisetts_path
        elsif action_name == 'edit'
            nisett_path
        end
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nisetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header"style=width:100%;">
          <%= link_to "Nisetter", root_path, class: "navbar-brand" %>
          <div class = "container" id="header-container"style=width:100%;">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown"style="max-width: 100px;float: right;">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">menu<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "新規投稿", new_nisett_path %></li>
                  <li><%= link_to "投稿一覧", nisetts_path %></li>
                  <li><%= link_to "メッセージ", new_message_path %></li>
                  <li><%= link_to "通知" %></li>
                  <li><%= link_to "友達つながり" %></li>
                  <li><%= link_to "ログイン" %></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
  </header>
<%= yield %>

  <footer>
    <p>運営会社　似せッター株式会社</p>
    <p>© 2015-2016 Copyright Nisetter Corp.</p>
  </footer>

</body>
</html>

app/views/messages/confirm.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <br>
    <h4>以下の内容で、送信する。</h4>
    <br>
    <br>
    <%= form_for(@message) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <p>名前：<%= @message.name %></p>
      <p>Eメール：<%= @message.email %></p>
      <p>内容：<%= @message.content %></p>
      <%= f.submit "送信",class:'btn btn-block' %>
    <% end %>

    <%= form_for(@message, url: new_message_path, method: 'get') do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる" , name:'back',class:'btn btn-default btn-block'%>
    <% end %>
  </div>
</div>

app/views/messages/new.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <br>
    <h3>メッセージを作成する</h3>
    <br>
    <br>
    <%= form_for(@message,url:confirm_messages_path) do |f| %>
      <% if @message.errors.any? %>
      <div id="error_explanation">
        <h2><%= @message.errors.count %>件のエラーがあります。</h2>
        
        <ul>
          <% @message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <br>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <br>
      <br>
      <%= f.label :content %>
      <%= f.text_field :content %>
      <br>
      <br>
      <%= f.submit'送信',class:'btn btn-block' %>
    <% end %>
  </div>
</div>

app/views/nisetts/_form.html.erb
<%= form_for(@nisett,url:choose_new_or_edit) do |f| %>
  <% if @nisett.errors.any? %>
    <div id="error_explanation">
        <h2><%= @nisett.errors.count %>件のエラーがあります。</h2>
        
        <ul>
        <% @nisett.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

  <%= f.label :"入力欄" %>
  <%= f.text_field :content,class:'form-control' %>
  <%= f.submit"投稿",class:'btn btn-block' %>
<% end %>

<%= link_to "投稿一覧", nisetts_path %>

app/views/nisetts/_ichiran.html.erb
<p id="notice"><strong><br><%= notice %></strong></p>
<%= link_to "新規投稿" , new_nisett_path,class:'btn btn-default' %>
<section class = "nisetts">
  <div class = "row">
    <br>
    <% @nisetts.each do |nisett| %>
      <div class = "nisett">
        <p><%= nisett.content %></p>
        <br>
        <%= link_to "編集",edit_nisett_path(nisett.id),class:'btn btn-default btn-sm btn-success' %>
        <%= link_to "削除", nisett_path(nisett.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn-danger' %>
      </div>
    <% end %>
  </div>
</section>

app/views/nisetts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h4>以下の内容で投稿していいですか？</h4>
    <%= form_for (@nisett) do |f| %>
      <%= f.hidden_field :content %>
      <p>本文：<%= @nisett.content %></p>
      <%= f.submit "投稿",class:'btn btn-block' %>
    <% end %>
  
    <%= form_for(@nisett, url: new_nisett_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる" , name:'back',class:'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/nisetts/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <br>
    <h3>編集する</h3>
    <br>
    <br>
    <%= render'form' %>
  </div>
</div>

app/views/nisetts/index.html.erb
<section class = "main-header">
  <img src="<%= asset_path"nisetter_white.png" %>">
</section>

<section class = "body container-fluid">
  <div class = "row">
    <div class = "gridcell col-md-3">
      <section class = "profile">
        <img src="<%= asset_path"profileavatar.png" %>">
        <h1>しらいし</h1>
          <p>
          制作課題実施中（似せッター）<br>
          戸惑いながらもコツコツ制作<br>
          </p>
  　
  　       <p>
            愛媛在住
          </p>
      </section>
    </div>
    
    <div class = "gridcell col-md-6">
      <section class= "ichiran">
        <%= render'nisetts/ichiran' %>
      </section>
    </div>
    
    <div class = "gridcell col-md-3 hidden-xs hidden-sm">
      <section class="function">
        <div class="function-images">
          <div class = "row">
          <div class="function-image">
            <img src="<%= asset_path"icon.png" %>">
            <p>モーメント</p>
          </div>
        </div>
        <div class = "row">
          <div class="function-image">
            <img src="<%= asset_path"icon.png" %>">
            <p>通知</p>
          </div>
        </div>
        <div class = "row">
          <div class="function-image">
            <img src="<%= asset_path"icon.png" %>">
            <p>友達つながり</p>
          </div>
        </div>
        <div class = "row">
          <div class="function-image">
            <img src="<%= asset_path"icon.png" %>">
              <p>コメント投稿</p>
          </div>
          <div id="page-top-btn" class="page-top-btn">
            <p><a class="move-page-top" id="move-page-top">▲</a></p>
          </div>
        </div>
      </section>
    </div>
</section>

app/views/nisetts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <br>
    <h3>投稿する</h3>
    <br>
    <br>
    <%= render'form' %>
  </div>
</div>

app/views/top/index.html.erb
<div class="container" id="top">
　<section class = "top-img">
    <div class="row">
      <img src="<%= asset_path"nisetter_top.png" %>">    
    </div>
  </section>
  <section class = "top-text">
    <div class = "row">
      <p>Twitterに似せて作成した</p>
      <p>練習用サイトです</p>
    </div>
  </section>
</div>